version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.8.2
      - test-3.8.1
      - test-3.8.0
      - test-3.7.7
      - test-3.7.4
      - test-3.7.3
      - test-3.7.2
      - test-3.7.1
      - test-3.7.0
      - test-3.6.10
      - test-3.6.9
      - test-3.6.8
      - test-3.6.7
      - test-3.6.6
      - test-3.6.5
      - test-3.6.4
      - test-3.6.3
jobs:
  test-3.8.2: &template
    docker:
      - image: python:3.8.2
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            python3 setup.py test
  test-3.8.1:
    <<: *template
    docker:
      - image: python:3.8.1
  test-3.8.0:
    <<: *template
    docker:
      - image: python:3.8.0
  test-3.7.7:
    <<: *template
    docker:
      - image: python:3.7.7
  test-3.7.6:
    <<: *template
    docker:
      - image: python:3.7.6
  test-3.7.5:
    <<: *template
    docker:
      - image: python:3.7.5
  test-3.7.4:
    <<: *template
    docker:
      - image: python:3.7.4
  test-3.7.3:
    <<: *template
    docker:
      - image: python:3.7.3
  test-3.7.2:
    <<: *template
    docker:
      - image: python:3.7.2
  test-3.7.1:
    <<: *template
    docker:
      - image: python:3.7.1
  test-3.7.0:
    <<: *template
    docker:
      - image: python:3.7.0
  test-3.6.10:
    <<: *template
    docker:
      - image: python:3.6.10
  test-3.6.9:
    <<: *template
    docker:
      - image: python:3.6.9
  test-3.6.8:
    <<: *template
    docker:
      - image: python:3.6.8
  test-3.6.7:
    <<: *template
    docker:
      - image: python:3.6.7
  test-3.6.6:
    <<: *template
    docker:
      - image: python:3.6.6
  test-3.6.5:
    <<: *template
    docker:
      - image: python:3.6.5
  test-3.6.4:
    <<: *template
    docker:
      - image: python:3.6.4
  test-3.6.3:
    <<: *template
    docker:
      - image: python:3.6.3
